language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Pedalino/pedalino.ino
    - PLATFORMIO_CI_SRC=PedalinoESP8266/PedalinoESP8266.ino
    - PLATFORMIO_CI_SRC=path/to/test/directory

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --board=<ID_1> --board=<ID_2> --board=<ID_N>
