language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Pedalino PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560 --project-option='lib_deps=Wire;lib_ignore=RobotIRremote'"
    - PLATFORMIO_CI_SRC=PedalinoESP8266 PLATFORMIO_CI_EXTRA_ARGS="--board=esp01_1m"

install:
    - pip install -U platformio
    - platformio update
    #
    # Libraries from PlatformIO Library Registry:
    #
    - platformio lib -g install 136
                                https://github.com/lathoub/Arduino-AppleMIDI-Library.git
                                https://github.com/FortySevenEffects/arduino_midi_library.git
                                https://github.com/thomasfredericks/Bounce2.git
                                https://github.com/dxinteractive/ResponsiveAnalogRead.git
                                https://github.com/MajicDesigns/MD_Menu.git
                                https://github.com/MajicDesigns/MD_UISwitch.git
                                https://github.com/z3t0/Arduino-IRremote.git
                                  
    #- wget https://raw.githubusercontent.com/alf45tar/Pedalino/master/platformio.ini -O /tmp/platformio.ini
    
    # download library to the temporary directory
   
    #- wget https://github.com/FortySevenEffects/arduino_midi_library/archive/master.zip -O /tmp/arduino_midi_library_source.zip
    #- unzip /tmp/arduino_midi_library_source.zip -d /tmp/
    
    #- wget https://github.com/thomasfredericks/Bounce2/archive/master.zip -O /tmp/Bounce2_source.zip
    #- unzip /tmp/Bounce2_source.zip -d /tmp/

    #- wget https://github.com/MajicDesigns/MD_Menu/archive/master.zip -O /tmp/MD_Menu_source.zip
    #- unzip /tmp/MD_Menu_source.zip -d /tmp/

    #- wget https://github.com/MajicDesigns/MD_UISwitch/archive/master.zip -O /tmp/MD_UISwitch_source.zip
    #- unzip /tmp/MD_UISwitch_source.zip -d /tmp/

    #- wget https://github.com/dxinteractive/ResponsiveAnalogRead/archive/master.zip -O /tmp/ResponsiveAnalogRead_source.zip
    #- unzip /tmp/ResponsiveAnalogRead_source.zip -d /tmp/

    #- wget https://github.com/z3t0/Arduino-IRremote/archive/master.zip -O /tmp/Arduino-IRremote_source.zip
    #- unzip /tmp/Arduino-IRremote_source.zip -d /tmp/

script:
    -  platformio ci $PLATFORMIO_CI_EXTRA_ARGS
