language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/avr PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560 --project-option='lib_ignore=RobotIRremote'"
    - PLATFORMIO_CI_SRC=src/esp PLATFORMIO_CI_EXTRA_ARGS="--board=esp01_1m"
    - PLATFORMIO_CI_SRC=src/esp PLATFORMIO_CI_EXTRA_ARGS="--board=esp12e"
    - PLATFORMIO_CI_SRC=src/esp PLATFORMIO_CI_EXTRA_ARGS="--board=esp32dev"
    - PLATFORMIO_CI_SRC=src/esp PLATFORMIO_CI_EXTRA_ARGS="--board=esp32doit-devkit-v1"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 62 64 136 222 415 423 1106 1194 1266 1674 1954
                                https://github.com/dxinteractive/ResponsiveAnalogRead.git
                                https://github.com/z3t0/Arduino-IRremote.git

script:
    -  platformio ci $PLATFORMIO_CI_EXTRA_ARGS --project-option="lib_deps=Wire" --project-option="board_build.partitions=no_ota.csv"
    
deploy-no:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
