language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Pedalino
    - PLATFORMIO_CI_SRC=PedalinoESP

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 62 136 222 423 1106 1266 1674 1954
                                https://github.com/dxinteractive/ResponsiveAnalogRead.git
                                https://github.com/z3t0/Arduino-IRremote.git

script:
    -  platformio ci --project-conf=platformio.ini

deploy-no:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
