language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Pedalino PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560 --project-option='lib_ignore=RobotIRremote'"
    - PLATFORMIO_CI_SRC=PedalinoESP PLATFORMIO_CI_EXTRA_ARGS="--board=esp01_1m"
    - PLATFORMIO_CI_SRC=PedalinoESP PLATFORMIO_CI_EXTRA_ARGS="--board=esp12e"
    - PLATFORMIO_CI_SRC=PedalinoESP PLATFORMIO_CI_EXTRA_ARGS="--board=esp32dev --board_build.partitions=no_ota.csv"
    - PLATFORMIO_CI_SRC=PedalinoESP PLATFORMIO_CI_EXTRA_ARGS="--board=esp32doit-devkit-v1 --board_build.partitions=no_ota.csv"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 62 136 222 423 1106 1266 1674 1954
                                https://github.com/dxinteractive/ResponsiveAnalogRead.git
                                https://github.com/z3t0/Arduino-IRremote.git

script:
    -  platformio ci $PLATFORMIO_CI_EXTRA_ARGS --project-option="lib_deps=Wire"

deploy-no:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
